services:
  mi-mongo-1:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: mi-mongo-1
    ports:
      - "27017:27017"
    networks:
      - mi-red-1
    volumes:
      - mi-vol-1:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    stdin_open: true
    tty: true

  mi-mongo-express-1:
    image: mongo-express:latest
    container_name: mi-mongo-express-1
    ports:
      - "9090:80"
    networks:
      - mi-red-1
    environment:
      - ME_CONFIG_MONGODB_SERVER=mi-mongo-1
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    stdin_open: true
    tty: true

networks:
  mi-red-1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16

volumes:
  mi-vol-1: